# Generated by Django 4.0.5 on 2022-06-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemImage',
            field=models.FileField(default='default.jpg', upload_to='static/image/item'),
        ),
    ]
